# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: windows-latest
    steps:
    # Checkout
    - uses: actions/checkout@v3
    - name: Setup .NET
    #Build
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Publish
      run: dotnet publish idleslayer/idleslayer.csproj -c Release -o release --self-contained -p:PublishSingleFile=true -p:PublishTrimmed=true
    - name: Easy Zip Files
      uses: vimtor/action-zip@v1.1
      with:
        files: release\
        dest: idleslayer_win.zip
    # Latest Release
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        title: "Latest Build"
        files: |
          idleslayer_win.zip
          idleslayer_win2.zip
